POST http://localhost:8080/invokeMethod
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "Host": "console.tim.qq.com",
  "Action": "/v4/group_open_http_svc/get_group_info",
  "Header": {
    "Content-Type": "application/json"
  },
  "Param": {
    "key": "b680b732f3f4e3dcbc6c6e5257ca3c8745697cd889ffbb6fed15dad2bbb314e8",
    "sdkappid": 1400327902,
    "identifier": "administrator",
    "usersig": "",
    "random": "",
    "expiretime": 604800,
  },
  "Body": {
    "GroupIdList": [
      "a636b50b07924a64a2db404d3f62e6d1"
    ]
  }
}

###